### ISSUE TITLE
Tabs doesn't work

### ISSUE THREAD

**Issue by RMehta95** [eecs394-s17/MyVillage#17]
When you navigate away from the home page all the tabs disappear

**Comment by fretbuzz** [comment]
workaround via b09346fefc145873d288644511154753a14fdbe3

**Comment by fretbuzz** [comment]
Functionality equivalent to #5

**Comment by fretbuzz** [comment]
Reopened in 25ff0ecb532a573675888ed5a49f255f689a9208

**Comment by fretbuzz** [comment]
Will probably need to revise 3efe5484ae32d2649069817219d6812d741087e8 also in order to get tabs back

**Comment by fretbuzz** [comment]
Closed in f4d1743c73b873afc52f13c95c0fe79a3ab281a4
